server:
  port: 8080

spring:
  config:
    import: application-aws.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATASOURCE_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
jwt:
  secretKey: ${JWT_SECRET}
aws:
  s3:
    bucketName: ${S3_BUCKET_NAME}
    apiSecret: ${S3_API_KEY}
logging:
  level:
    org.springframework.security : DEBUG
    org.springframework.web : DEBUG