[project]
name = "beecareful-s3-lambda-handler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "urllib3>=2.4.0",
]
